apiVersion: v1
description: Creates Node GPU Exporter instance for Kubernetes which maintaining by Rancher 2.
engine: gotpl
maintainers:
- name: jiang
  email: jiang@xinhuotech.com
name: exporter-node-gpu
version: 0.0.1