{
 "title": "Nvidia GPU",
 "description": "GPU dashboard for nvidia metrics ",
 "tags": [
  "gpu",
  "cluster",
  "hardware",
  "infrastructure"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Host:",
    "query": "label_values(dcgm_enc_utilization, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 } },
  {
   "title": "GPU占用率",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "dcgm_gpu_utilization" }
   ]
  },
  {
   "title": "显存占用率",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "dcgm_mem_copy_utilization" }
   ]
  },
  {
   "title": "GPU占用率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "dcgm_gpu_utilization",
     "legendFormat": "{{kubernetes_pod_node_name}} - gpu{{minor}}"
    }
   ]
  },
  {
   "title": "内存占用率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "dcgm_mem_copy_utilization",
     "legendFormat": "{{kubernetes_pod_node_name}} - gpu{{minor}}"
    }
   ]
  },
  {
   "title": "# GPUs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(nvidia_device_count)" }
   ]
  },
  {
   "title": "GPU温度",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "dcgm_gpu_temp",
     "legendFormat": "{{kubernetes_pod_node_name}} - gpu{{minor}}"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "mwatt" }
   ],
   "targets": [
    {
     "expr": "dcgm_power_usage",
     "legendFormat": "{{kubernetes_pod_node_name}} - gpu{{minor}}"
    }
   ]
  },
  {
   "title": "GPU PCIe接收",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    { "expr": "dcgm_pcie_rx_throughput", "legendFormat": "{{kubernetes_pod_node_name}}" }
   ]
  },
  {
   "title": "GPU PCIe发送",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    { "expr": "dcgm_pcie_tx_throughput" }
   ]
  }
 ]
}